### ISSUE TITLE
Problem building app

### ISSUE THREAD

**Issue by Jayce53** [versatica/mediasoup-demo#15]
```
localhost:~/mediasoup-demo/app$ gulp dist
[18:51:59] NODE_ENV: development
[18:51:59] Using gulpfile ~/mediasoup-demo/app/gulpfile.js
[18:51:59] Starting 'dist'...
[18:51:59] Starting 'clean'...
[18:51:59] Finished 'clean' after 96 ms
[18:51:59] Starting 'lint'...
[18:52:02] Finished 'lint' after 3.18 s
[18:52:02] Starting 'bundle'...
[18:52:17] Plumber found unhandled error:
 Error: Received a non-Vinyl object in `dest()`
[18:52:17] 'bundle' errored after 15 s
[18:52:17] Error: premature close
    at Pumpify.onclose (/home/larissa/mediasoup-demo/app/node_modules/end-of-stream/index.js:43:67)
    at emitNone (events.js:111:20)
    at Pumpify.emit (events.js:208:7)
    at Pumpify.Duplexify._destroy (/home/larissa/mediasoup-demo/app/node_modules/duplexify/index.js:192:8)
    at /home/larissa/mediasoup-demo/app/node_modules/duplexify/index.js:175:10
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[18:52:17] 'dist' errored after 19 s

```
Running on Ubuntu 16.04.3
```
localhost:~/mediasoup-demo/app$ gulp -v
[19:09:22] CLI version 2.0.0
[19:09:22] Local version 4.0.0-alpha.3
```

**Comment by ibc** [comment]
Confirmed that it also happens in OSX.

**Comment by ibc** [comment]
Some dependency caused the problem. It seems to be fixed once updated all the dependencies to their latest NPM version. So run `npm update` and try again.

Thanks for reporting.
