### ISSUE TITLE
Unable to run application on Ubuntu 16.04

### ISSUE THREAD

**Issue by dholgaurav** [versatica/mediasoup-demo#21]
Hi,

I have pulled the code and followed ReadMe document instructions when I run server application it display following error.

- process.env.DEBUG: *INFO* *WARN* *ERROR* *mediasoup-worker*
- config.mediasoup.logLevel: warn
- config.mediasoup.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp', 'rbe', 'rtx' ]
/home/gaurav/Desktop/SourceCode/mediasoup-demo/server/node_modules/mediasoup/lib/EnhancedEventEmitter.js:16
	safeEmit(event, ...args)
	                ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/gaurav/Desktop/SourceCode/mediasoup-demo/server/node_modules/mediasoup/lib/Server.js:7:30)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

--------------------------------------------------

When i try to run client application it gives me  following error

gaurav@ubuntu:~/Desktop/SourceCode/mediasoup-demo/app$ sudo gulp live
[sudo] password for gaurav: 
/home/gaurav/Desktop/SourceCode/mediasoup-demo/app/gulpfile.js:65
	let bundler = browserify(
	^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:36:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:203:12)

Please let me know if i have to add some packages or do some configuration
If  mediasoup is not supported on Ubuntu 16.04 then please let me know the supported OS and configurations steps if possible.

Regards,
Gaurav Dhol

**Comment by ibc** [comment]
Check the minimum Node version required in package.json files.

**Comment by dholgaurav** [comment]
I am not able to find minimum node version in package.json 
I am using v4.2.6 version

**Comment by ibc** [comment]
What can I say?:

https://github.com/versatica/mediasoup/blob/master/package.json#L28

https://mediasoup.org/documentation/mediasoup/installation/

**Comment by dholgaurav** [comment]
Thanks 
I am able to run after upgrade to 9.4.0
