### ISSUE TITLE
Problem installing the demo

### ISSUE THREAD

**Issue by Ataru73** [versatica/mediasoup-demo#30]
Hi all,
I'm trying to install the demo. 
I'm stuck at the 'npm install' pass on the server side. npm fails with this error when it thies to install mediasoup@2.1.0 on an Ubuntu server 16.04.

```
cd worker && /usr/bin/python2 ./scripts/configure.py -R mediasoup-worker
Traceback (most recent call last):
  File "./scripts/configure.py", line 84, in <module>
    (major, minor), is_clang = compiler_version()
  File "./scripts/configure.py", line 37, in compiler_version
    proc = subprocess.Popen(CC.split() + ['--version'], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:19: recipe for target 'Release' failed
make: *** [Release] Error 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mediasoup@2.1.0 postinstall: `make Release`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mediasoup@2.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Any clue?

Thanks.

-A

**Comment by ibc** [comment]
Please, forget the demo and just try to install mediasoup using npm:

https://mediasoup.org/documentation/mediasoup/installation/

If it fails, ensure you satisfy the requirement list.

NOTE: I will close this issue since mediasoup possible issues do not belong to the demo project. Feel free to continue the conversation in the mediasoup public mailing list (Google Group). Thanks.
