### ISSUE TITLE
mediasoup:ERROR TypeError: cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by stodi1** [versatica/mediasoup-demo#47]
I am trying to start the demo, I followed the instruction to install the server. When I try to run the server with:

node server.js
or
DEBUG="*mediasoup* *ERROR* *WARN*" INTERACTIVE="true" node server.js

it's throwing the error mentioned in the title with the stack trace:

mediasoup:ERROR "unhandledRejection" event (Promise rejected with no error handler):
mediasoup:ERROR TypeError: Cannot read property 'on' of undefined
    at runMediasoupObserver (/home/abdou/mediasoup-demo/server/lib/interactiveServer.js:428:21)
    at module.exports (/home/abdou/mediasoup-demo/server/lib/interactiveServer.js:477:2)
    at run (/home/abdou/mediasoup-demo/server/server.js:63:8)
    at Object.<anonymous> (/home/abdou/mediasoup-demo/server/server.js:58:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10) +0ms

Ps: I used the npm registry to install the mediasoup module "npm install mediasoup" instead of the git repo as I am behind a proxy and I couldn't resolve the git repo (yes, I tried to configure the git proxy but couldn't resolve the problem).

**Comment by ibc** [comment]
mediasoup v3 is not yet ready. The demo project "master" branch is hence not ready.

**Comment by stodi1** [comment]
I am using the version 2.6.12 but still facing the same problem

**Comment by ibc** [comment]
Logs above are from the mediasoup-demo "master" branch which uses mediasoup "master" branch (version 3 not yet ready), sorry.

**Comment by stodi1** [comment]
Sorry, my mistake, can I use the demo if I switch to v2 branch? (Just for testing, I actually need just the server)

**Comment by ibc** [comment]
You can checkout the "v2" branch of the mediasoup-demo project.
