### ISSUE TITLE
Error: Cannot find module 'tsc-watch/client'

### ISSUE THREAD

**Issue by Nemocdz** [versatica/mediasoup-demo#62]
Install server demo, use `npm install`.
Node Version: v12.13.0
NPM Version: 6.12.0
```
$ npm install

> fsevents@1.2.9 install /Users/nemo/Dev/WeGameXAudio/mediasoup-demo/server/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/nemo/Dev/WeGameXAudio/mediasoup-demo/server/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> websocket@1.0.30 install /Users/nemo/Dev/WeGameXAudio/mediasoup-demo/server/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> clang-tools-prebuilt@0.1.4 postinstall /Users/nemo/Dev/WeGameXAudio/mediasoup-demo/server/node_modules/clang-tools-prebuilt
> node install.js

unziping /Users/nemo/.clang-tools/clang-tools-r298696-mac.tgz

> mediasoup@3.3.0-pre1 postinstall /Users/nemo/Dev/WeGameXAudio/mediasoup-demo/server/node_modules/mediasoup
> node npm-scripts.js postinstall

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'tsc-watch/client'
Require stack:
- /Users/nemo/Dev/WeGameXAudio/mediasoup-demo/server/node_modules/mediasoup/npm-scripts.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/nemo/Dev/WeGameXAudio/mediasoup-demo/server/node_modules/mediasoup/npm-scripts.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/nemo/Dev/WeGameXAudio/mediasoup-demo/server/node_modules/mediasoup/npm-scripts.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.3.0-pre1 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mediasoup@3.3.0-pre1 postinstall script.
```

**Comment by ibc** [comment]
Fixed in mediasoup and mediasoup-client "devel" branches
