### ISSUE TITLE
Error: Cannot find module 'tsc-watch/client'

### ISSUE THREAD

**Issue by 377123** [versatica/mediasoup-demo#63]
npm install  

> mediasoup@3.3.0-pre1 postinstall /wwwroot/mediasoup-demo/server/node_modules/mediasoup
> node npm-scripts.js postinstall

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'tsc-watch/client'
Require stack:
- /wwwroot/mediasoup-demo/server/node_modules/mediasoup/npm-scripts.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/wwwroot/mediasoup-demo/server/node_modules/mediasoup/npm-scripts.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/wwwroot/mediasoup-demo/server/node_modules/mediasoup/npm-scripts.js'
  ]
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN network SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npm.taobao.org/fsevents failed, reason: getaddrinfo ENOTFOUND registry.npm.taobao.org

**Comment by ibc** [comment]
Yep, fixed now.

**Comment by ibc** [comment]
Did you ever check existing issues? #62 62
