### ISSUE TITLE
ERROR:Client pc.getStats() failed

### ISSUE THREAD

**Issue by jonahzheng** [versatica/mediasoup-demo#7]
mediasoup-demo:ERROR:Client pc.getStats() failed: TypeError: Failed to execute 'getStats' on 'RTCPeerConnection': No function was found that matched the signature provided.
    at Client.getStats (https://192.168.0.209:3000/mediasoup-demo-app.js:477:32)
    at Room.getStats (https://192.168.0.209:3000/mediasoup-demo-app.js:2382:18)
    at Room._startStats (https://192.168.0.209:3000/mediasoup-demo-app.js:2377:13)

**Comment by ibc** [comment]
Please, provide much more info. Which browser?

**Comment by jonahzheng** [comment]
browser is google chrome

**Comment by ibc** [comment]
Closing since this no longer affects the new v2 based demo.
