### ISSUE TITLE
ENOENT privkey.pem

### ISSUE THREAD

**Issue by Sanix-Darker** [versatica/mediasoup-demo#75]
i got an error after following all your steps when i tried to start app qith :

```
cd app
npm start
```
Error:
```
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/mediasoup-demo/server/certs/privkey.pem'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at getKey (/home/mediasoup-demo/app/node_modules/browser-sync/dist/server/utils.js:38:15)
    at getHttpsServerDefaults (/home/mediasoup-demo/app/node_modules/browser-sync/dist/server/utils.js:45:14)
    at Object.getHttpsOptions (/home/mediasoup-demo/app/node_modules/browser-sync/dist/server/utils.js:67:41)
    at /home/mediasoup-demo/app/node_modules/browser-sync/dist/server/utils.js:81:44
    at Object.getServer (/home/mediasoup-demo/app/node_modules/browser-sync/dist/server/utils.js:85:15)
    at createServer (/home/mediasoup-demo/app/node_modules/browser-sync/dist/server/static-server.js:71:24)
    at createServer (/home/mediasoup-demo/app/node_modules/browser-sync/dist/server/index.js:72:42)
    at module.exports.plugin (/home/mediasoup-demo/app/node_modules/browser-sync/dist/server/index.js:12:20) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/mediasoup-demo/server/certs/privkey.pem'
}
```

How can i resolve it please ?

**Comment by ibc** [comment]
Generate your own valid certs.

Please use the forum for usage questions.

**Comment by Sanix-Darker** [comment]
Is this suppose to help me ?
Can you provide a quick tip to do it please ?

**Comment by ibc** [comment]
No, sorry. You can do a quick search in Google.

**Comment by Sanix-Darker** [comment]
Ok ok, i finally found out how to create it using cerbot, but when am trying with localhost it's not working, am getting :

```
An unexpected error occurred:
The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "localhost": Domain name needs at least one dot
```

How can i run it locally then ?

By the way, in other part, i tried comment `tls` on config.js but am having issues with webSocket Server !

A little help please !

**Comment by Sanix-Darker** [comment]
My command was :
```
./certbot-auto certonly --webroot -w /home/mediasoup-demo/server/certs -d localhost
```

**Comment by Sanix-Darker** [comment]
OK, i saw in server.js, the https server can not run without `tls` parameters !

**Comment by ibc** [comment]
Sorry, this is not a help forum. I already said "please use the forum for usage/support questions".
