### ISSUE TITLE
Npm install failed 

### ISSUE THREAD

**Issue by chamikara1998** [versatica/mediasoup-demo#88]
Mediasoup npm install failed. Tried on Mac OS X Mojave and centos system. both failed.

I also updated python => python 3
gcc => 9.1
make => GNU Make 3.82

This is the result of centos 7.0

Traceback (most recent call last): File "./scripts/configure.py", line 111, in <module> run_gyp(gyp_args) File "./scripts/configure.py", line 49, in run_gyp rc = gyp.main(args) File "./deps/gyp/pylib/gyp/__init__.py", line 545, in main return gyp_main(args) File "./deps/gyp/pylib/gyp/__init__.py", line 530, in gyp_main generator.GenerateOutput(flat_list, targets, data, params) File "./deps/gyp/pylib/gyp/generator/make.py", line 2210, in GenerateOutput part_of_all=qualified_target in needed_targets) File "./deps/gyp/pylib/gyp/generator/make.py", line 820, in Write self.Pchify)) File "./deps/gyp/pylib/gyp/generator/make.py", line 1215, in WriteSources cflags = self.xcode_settings.GetCflags(configname) File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 630, in GetCflags archs = self.GetActiveArchs(self.configname) File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 488, in GetActiveArchs xcode_archs_default = GetXcodeArchsDefault() File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 120, in GetXcodeArchsDefault xcode_version, _ = XcodeVersion() File "./deps/gyp/pylib/gyp/xcode_emulation.py", line 1409, in XcodeVersion version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0] AttributeError: 'NoneType' object has no attribute 'groups' make: *** [default] Error 1

then I tried with

CC=gcc-9.1 npm install

then I got

Traceback (most recent call last): File "./scripts/configure.py", line 83, in <module> (major, minor), is_clang = compiler_version() File "./scripts/configure.py", line 36, in compiler_version proc = subprocess.Popen(CC.split() + ['--version'], stdout=subprocess.PIPE) File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__ errread, errwrite) File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child raise child_exception OSError: [Errno 2] No such file or directory make: *** [default] Error 1

Please help me to solve this issue. Can I get a docker image for V3? I look forward to you as early as possible.

**Comment by ibc** [comment]
Oh, so you ask again for a mediasoup Docker image.

Python exact version, please. And try with Python 2.

**Comment by chamikara1998** [comment]
Tried with both python 2.7 and 3

**Comment by chamikara1998** [comment]
PYTHON=python2 CC=gcc-9.1 npm install

output 
`Traceback (most recent call last):
  File "./scripts/configure.py", line 83, in <module>
    (major, minor), is_clang = compiler_version()
  File "./scripts/configure.py", line 36, in compiler_version
    proc = subprocess.Popen(CC.split() + ['--version'], stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: *** [default] Error 1`

 PYTHON=python3 CC=gcc-9.1 npm install

output 

`Traceback (most recent call last):
  File "./scripts/configure.py", line 83, in <module>
    (major, minor), is_clang = compiler_version()
  File "./scripts/configure.py", line 36, in compiler_version
    proc = subprocess.Popen(CC.split() + ['--version'], stdout=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gcc-9.1': 'gcc-9.1'
make: *** [default] Error 1`

**Comment by ibc** [comment]
You have open 3 issues and one private email for this. Please use the issue open in mediasoup project and provide what it's told in there (clone mediasoup repo and run make in mediasoup/worker/ folder).
